version: "3.5"

services:

    files:
        image: node
        working_dir: /app
        command: sleep infinity
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
            - jellyfin_web_files:/app/dist

    nginx:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - jellyfin_web_files:/usr/share/nginx/html

volumes:
    node_modules:
    jellyfin_web_files:
